Fix country flags
Thrillberg/imperial-old pull request #62
Opened 2018-01-18 02:05 UTC by andrewmpierce

This is a really small change. It mostly fixes the country flags showing correctly. 

It looks like France and Italy are still behaving a little weirdly. It's showing the correct flag, but my guess is that its too zoomed in or something? I'm still messing around with that part.

2018-01-18 02:13 UTC, Thrillberg requested changes

2018-01-18 02:13 UTC, Thrillberg commented on app/views/svg/_france_flag.html.erb
> +  <rect width="300" height="600" fill="#002395"/>
Ah! I found it. Make these `rect`s 9x6, 6x6, and 3x6, instead of 900x600, 600x600, and 300x600. I think that will solve the zooming problem. Oh and check out if the `width` and `height` of the `svg` are correct too... maybe they need the zeroes removed too?

2018-01-21 03:38 UTC, andrewmpierce commented
I did some messing around and now the flags work!

<img width="521" alt="screen shot 2018-01-20 at 10 37 10 pm" src="https://user-images.githubusercontent.com/11707173/35190565-9fc2aa10-fe32-11e7-8cf3-74249e96cbf3.png">

2018-01-21 12:20 UTC, Thrillberg commented
Looks great! 👍

2018-01-21 12:20 UTC, Thrillberg approved these changes

2018-01-21 12:20 UTC, merged